version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/portainer:/data
    ports:
      - 9000:9000

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - /opt/homeassistant/addons/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host

  duplicati:
    image: duplicati/duplicati:linux-arm32v7-latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /opt:/source
    ports:
      - 8200:8200
    restart: unless-stopped

  adguard:
    container_name: adguardhome
    image: adguard/adguardhome
    environment:
      - TZ=Europe/Paris
    volumes:
      - /opt/adguardhome/work:/work
      - /opt/adguardhome/conf:/conf
    ports:
      - 53:53/tcp  # port DNS
      - 53:53/udp  # port DNS
      - 67:67/udp  # port DHCP serveur BOOTP
#      - 68:68/tcp  # port DHCP client BOOTP
#      - 68:68/udp  # port DHCP client BOOTP
      - 80:80/tcp  # port HTTP
#      - 443:443/tcp  # port HTTPS
      - 853:853/tcp  # port DNS over TLS
      - 3000:3000/tcp  # port HTTP temporaire pour la première configuration d'AdGuard
#    network_mode: host  # nécessaire si AdGuard Home est utilisé en tant que serveur DHCP
    restart: unless-stopped
